name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  book-and-midi:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y libjack-jackd2-0 libnss3 libegl1 libegl1-mesa libegl-mesa0 xvfb
    - name: Download MuseScore 3.6
      run: |
        wget -c https://github.com/musescore/MuseScore/releases/download/v3.6/MuseScore-3.6.0.487916429-x86_64.AppImage
        chmod +x MuseScore-3.6.0.487916429-x86_64.AppImage
    - name: Generate PDF Songbook
      run: |
        xvfb-run -- ./make_book.sh ./MuseScore-3.6.0.487916429-x86_64.AppImage
    - name: Upload PDF songbook
      uses: actions/upload-artifact@v2
      with:
        name: "songbook-pdf"
        path: "Church Songbook.pdf"
    - name: Generate MIDI files
      run: |
        xvfb-run -- ./make_midi.sh ./MuseScore-3.6.0.487916429-x86_64.AppImage
    - name: Upload MIDI files
      uses: actions/upload-artifact@v2
      with:
        name: songbook-midi
        path: MIDIs/**/*.mid
