name: Build

on:
  push:
    tags:
      - '*'

jobs:
  book-and-midi:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y libjack-jackd2-0 libnss3 libegl1 libegl1-mesa libegl-mesa0 xvfb ghostscript texlive texlive-xetex
    - name: Download MuseScore 3.6
      run: |
        wget --quiet --continue https://github.com/musescore/MuseScore/releases/download/v3.6.2/MuseScore-3.6.2.548021370-x86_64.AppImage
        chmod +x MuseScore-3.6.2.548021370-x86_64.AppImage
    - name: Generate PDF Songbook
      run: |
        xvfb-run -- ./make_book.sh ./MuseScore-3.6.2.548021370-x86_64.AppImage
    - name: Generate MIDI files
      run: |
        xvfb-run -- ./make_midi.sh ./MuseScore-3.6.2.548021370-x86_64.AppImage
    - name: Add all generated MIDI files into Zip archive
      run: |
        zip songbook-midi.zip MIDIs/**/*.mid
    - name: Upload PDF songbook to a GitHub release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: "songbook.pdf"
        tag: ${{ github.ref }}
        overwrite: true
    - name: Upload MIDI files to a GitHub release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: "songbook-midi.zip"
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
